/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package de.silver.avro;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface OrderProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"OrderProtocol\",\"namespace\":\"de.silver.avro\",\"types\":[{\"type\":\"record\",\"name\":\"Order\",\"fields\":[{\"name\":\"customerId\",\"type\":[\"string\",\"null\"]},{\"name\":\"productId\",\"type\":\"string\"},{\"name\":\"nrOfItems\",\"type\":[\"int\",\"null\"]},{\"name\":\"comment\",\"type\":[\"string\",\"null\"]}]},{\"type\":\"error\",\"name\":\"StoreException\",\"fields\":[{\"name\":\"message\",\"type\":[\"string\",\"null\"]}]}],\"messages\":{\"storeOrder\":{\"request\":[{\"name\":\"order\",\"type\":\"Order\"}],\"response\":\"string\",\"errors\":[\"StoreException\"]},\"existsProduct\":{\"request\":[{\"name\":\"productId\",\"type\":\"string\"}],\"response\":\"boolean\"}}}");
  /**
   */
  java.lang.CharSequence storeOrder(de.silver.avro.Order order) throws org.apache.avro.AvroRemoteException, de.silver.avro.StoreException;
  /**
   */
  boolean existsProduct(java.lang.CharSequence productId) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends OrderProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = de.silver.avro.OrderProtocol.PROTOCOL;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void storeOrder(de.silver.avro.Order order, org.apache.avro.ipc.Callback<java.lang.CharSequence> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void existsProduct(java.lang.CharSequence productId, org.apache.avro.ipc.Callback<java.lang.Boolean> callback) throws java.io.IOException;
  }
}