/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package de.silver.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class StoreException extends org.apache.avro.specific.SpecificExceptionBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5588930132502668940L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"error\",\"name\":\"StoreException\",\"namespace\":\"de.silver.avro\",\"fields\":[{\"name\":\"message\",\"type\":[\"string\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence message$;

  public StoreException() {
    super();
  }
  
  public StoreException(Object value) {
    super(value);
  }

  public StoreException(Throwable cause) {
    super(cause);
  }

  public StoreException(Object value, Throwable cause) {
    super(value, cause);
  }
  
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return message$;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: message$ = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'message$' field.
   */
  public java.lang.CharSequence getMessage$() {
    return message$;
  }

  /**
   * Sets the value of the 'message$' field.
   * @param value the value to set.
   */
  public void setMessage$(java.lang.CharSequence value) {
    this.message$ = value;
  }

  /**
   * Creates a new StoreException RecordBuilder.
   * @return A new StoreException RecordBuilder
   */
  public static de.silver.avro.StoreException.Builder newBuilder() {
    return new de.silver.avro.StoreException.Builder();
  }
  
  /**
   * Creates a new StoreException RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new StoreException RecordBuilder
   */
  public static de.silver.avro.StoreException.Builder newBuilder(de.silver.avro.StoreException.Builder other) {
    return new de.silver.avro.StoreException.Builder(other);
  }
  
  /**
   * Creates a new StoreException RecordBuilder by copying an existing StoreException instance.
   * @param other The existing instance to copy.
   * @return A new StoreException RecordBuilder
   */
  public static de.silver.avro.StoreException.Builder newBuilder(de.silver.avro.StoreException other) {
    return new de.silver.avro.StoreException.Builder(other);
  }
  
  /**
   * RecordBuilder for StoreException instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificErrorBuilderBase<StoreException>
    implements org.apache.avro.data.ErrorBuilder<StoreException> {

    private java.lang.CharSequence message$;

    /** Creates a new Builder */
    private Builder() {
      super(de.silver.avro.StoreException.SCHEMA$);
    }
    
    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(de.silver.avro.StoreException.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.message$)) {
        this.message$ = data().deepCopy(fields()[0].schema(), other.message$);
        fieldSetFlags()[0] = true;
      }
    }
    
    /**
     * Creates a Builder by copying an existing StoreException instance
     * @param other The existing instance to copy.
     */
    private Builder(de.silver.avro.StoreException other) {
      super(other);
      if (isValidValue(fields()[0], other.message$)) {
        this.message$ = data().deepCopy(fields()[0].schema(), other.message$);
        fieldSetFlags()[0] = true;
      }
    }

    @Override
    public de.silver.avro.StoreException.Builder setValue(Object value) {
      super.setValue(value);
      return this;
    }
    
    @Override
    public de.silver.avro.StoreException.Builder clearValue() {
      super.clearValue();
      return this;
    }

    @Override
    public de.silver.avro.StoreException.Builder setCause(Throwable cause) {
      super.setCause(cause);
      return this;
    }
    
    @Override
    public de.silver.avro.StoreException.Builder clearCause() {
      super.clearCause();
      return this;
    }

    /**
      * Gets the value of the 'message$' field.
      * @return The value.
      */
    public java.lang.CharSequence getMessage$() {
      return message$;
    }

    /**
      * Sets the value of the 'message$' field.
      * @param value The value of 'message$'.
      * @return This builder.
      */
    public de.silver.avro.StoreException.Builder setMessage$(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.message$ = value;
      fieldSetFlags()[0] = true;
      return this; 
    }

    /**
      * Checks whether the 'message$' field has been set.
      * @return True if the 'message$' field has been set, false otherwise.
      */
    public boolean hasMessage$() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'message$' field.
      * @return This builder.
      */
    public de.silver.avro.StoreException.Builder clearMessage$() {
      message$ = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public StoreException build() {
      try {
        StoreException record = new StoreException(getValue(), getCause());
        record.message$ = fieldSetFlags()[0] ? this.message$ : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);  

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, org.apache.avro.specific.SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);  

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, org.apache.avro.specific.SpecificData.getDecoder(in));
  }

}
